apiVersion: v1
kind: PersistentVolume
metadata:
  name: opencart-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ubuntu/samir/mysqldata
